projects:
  app:
    schemaPath: api/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: api/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml